#include <ni/logging/common.hh>

namespace ni
{
namespace logging
{

constexpr const char* ERRNO_NAMES[] = {
  /*   0 */ "",
  /*   1 */ "EPERM", "ENOENT", "ESRCH", "EINTR", "EIO", "ENXIO", "E2BIG",
  /*   8 */ "ENOEXEC", "EBADF", "ECHILD", "EAGAIN/EWOULDBLOCK", "ENOMEM",
  /*  13 */ "EACCES", "EFAULT", "ENOTBLK", "EBUSY", "EEXIST", "EXDEV", "ENODEV",
  /*  20 */ "ENOTDIR", "EISDIR", "EINVAL", "ENFILE", "EMFILE", "ENOTTY",
  /*  26 */ "ETXTBSY", "EFBIG", "ENOSPC", "ESPIPE", "EROFS", "EMLINK", "EPIPE",
  /*  33 */ "EDOM", "ERANGE", "EDEADLK/EDEADLOCK", "ENAMETOOLONG", "ENOLCK",
  /*  38 */ "ENOSYS", "ENOTEMPTY", "ELOOP", "", "ENOMSG", "EIDRM", "ECHRNG",
  /*  45 */ "EL2NSYNC", "EL3HLT", "EL3RST", "ELNRNG", "EUNATCH", "ENOCSI",
  /*  51 */ "EL2HLT", "EBADE", "EBADR", "EXFULL", "ENOANO", "EBADRQC",
  /*  57 */ "EBADSLT", "", "EBFONT", "ENOSTR", "ENODATA", "ETIME", "ENOSR",
  /*  64 */ "ENONET", "ENOPKG", "EREMOTE", "ENOLINK", "EADV", "ESRMNT", "ECOMM",
  /*  71 */ "EPROTO", "EMULTIHOP", "EDOTDOT", "EBADMSG", "EOVERFLOW",
  /*  76 */ "ENOTUNIQ", "EBADFD", "EREMCHG", "ELIBACC", "ELIBBAD", "ELIBSCN",
  /*  82 */ "ELIBMAX", "ELIBEXEC", "EILSEQ", "ERESTART", "ESTRPIPE", "EUSERS",
  /*  88 */ "ENOTSOCK", "EDESTADDRREQ", "EMSGSIZE", "EPROTOTYPE", "ENOPROTOOPT",
  /*  93 */ "EPROTONOSUPPORT", "ESOCKTNOSUPPORT", "EOPNOTSUPP/ENOTSUP",
  /*  96 */ "EPFNOSUPPORT", "EAFNOSUPPORT", "EADDRINUSE", "EADDRNOTAVAIL",
  /* 100 */ "ENETDOWN", "ENETUNREACH", "ENETRESET", "ECONNABORTED",
  /* 104 */ "ECONNRESET", "ENOBUFS", "EISCONN", "ENOTCONN", "ESHUTDOWN",
  /* 109 */ "ETOOMANYREFS", "ETIMEDOUT", "ECONNREFUSED", "EHOSTDOWN",
  /* 113 */ "EHOSTUNREACH", "EALREADY", "EINPROGRESS", "ESTALE", "EUCLEAN",
  /* 118 */ "ENOTNAM", "ENAVAIL", "EISNAM", "EREMOTEIO", "EDQUOT", "ENOMEDIUM",
  /* 124 */ "EMEDIUMTYPE", "ECANCELED", "ENOKEY", "EKEYEXPIRED", "EKEYREVOKED",
  /* 129 */ "EKEYREJECTED", "EOWNERDEAD", "ENOTRECOVERABLE", "ERFKILL",
  /* 133 */ "EHWPOISON"
};

} // namespace logging
} // namespace ni
