// Copyright (C) 2016 Zhe Wang <0x1998@gmail.com>
//
// Permission is hereby granted, free of charge, to any person obtaining a copy
// of this software and associated documentation files (the "Software"), to deal
// in the Software without restriction, including without limitation the rights
// to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
// copies of the Software, and to permit persons to whom the Software is
// furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in
// all copies or substantial portions of the Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
// IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.  IN NO EVENT SHALL THE
// AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
// LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
// OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
// THE SOFTWARE.
#include <ni/logging/common.hh>

namespace ni
{
namespace logging
{

constexpr const char* ERRNO_NAMES[] = {"",
                                       "EPERM",
                                       "ENOENT",
                                       "ESRCH",
                                       "EINTR",
                                       "EIO",
                                       "ENXIO",
                                       "E2BIG",
                                       "ENOEXEC",
                                       "EBADF",
                                       "ECHILD",
                                       "EAGAIN/EWOULDBLOCK",
                                       "ENOMEM",
                                       "EACCES",
                                       "EFAULT",
                                       "ENOTBLK",
                                       "EBUSY",
                                       "EEXIST",
                                       "EXDEV",
                                       "ENODEV",
                                       "ENOTDIR",
                                       "EISDIR",
                                       "EINVAL",
                                       "ENFILE",
                                       "EMFILE",
                                       "ENOTTY",
                                       "ETXTBSY",
                                       "EFBIG",
                                       "ENOSPC",
                                       "ESPIPE",
                                       "EROFS",
                                       "EMLINK",
                                       "EPIPE",
                                       "EDOM",
                                       "ERANGE",
                                       "EDEADLK/EDEADLOCK",
                                       "ENAMETOOLONG",
                                       "ENOLCK",
                                       "ENOSYS",
                                       "ENOTEMPTY",
                                       "ELOOP",
                                       "",
                                       "ENOMSG",
                                       "EIDRM",
                                       "ECHRNG",
                                       "EL2NSYNC",
                                       "EL3HLT",
                                       "EL3RST",
                                       "ELNRNG",
                                       "EUNATCH",
                                       "ENOCSI",
                                       "EL2HLT",
                                       "EBADE",
                                       "EBADR",
                                       "EXFULL",
                                       "ENOANO",
                                       "EBADRQC",
                                       "EBADSLT",
                                       "",
                                       "EBFONT",
                                       "ENOSTR",
                                       "ENODATA",
                                       "ETIME",
                                       "ENOSR",
                                       "ENONET",
                                       "ENOPKG",
                                       "EREMOTE",
                                       "ENOLINK",
                                       "EADV",
                                       "ESRMNT",
                                       "ECOMM",
                                       "EPROTO",
                                       "EMULTIHOP",
                                       "EDOTDOT",
                                       "EBADMSG",
                                       "EOVERFLOW",
                                       "ENOTUNIQ",
                                       "EBADFD",
                                       "EREMCHG",
                                       "ELIBACC",
                                       "ELIBBAD",
                                       "ELIBSCN",
                                       "ELIBMAX",
                                       "ELIBEXEC",
                                       "EILSEQ",
                                       "ERESTART",
                                       "ESTRPIPE",
                                       "EUSERS",
                                       "ENOTSOCK",
                                       "EDESTADDRREQ",
                                       "EMSGSIZE",
                                       "EPROTOTYPE",
                                       "ENOPROTOOPT",
                                       "EPROTONOSUPPORT",
                                       "ESOCKTNOSUPPORT",
                                       "EOPNOTSUPP/ENOTSUP",
                                       "EPFNOSUPPORT",
                                       "EAFNOSUPPORT",
                                       "EADDRINUSE",
                                       "EADDRNOTAVAIL",
                                       "ENETDOWN",
                                       "ENETUNREACH",
                                       "ENETRESET",
                                       "ECONNABORTED",
                                       "ECONNRESET",
                                       "ENOBUFS",
                                       "EISCONN",
                                       "ENOTCONN",
                                       "ESHUTDOWN",
                                       "ETOOMANYREFS",
                                       "ETIMEDOUT",
                                       "ECONNREFUSED",
                                       "EHOSTDOWN",
                                       "EHOSTUNREACH",
                                       "EALREADY",
                                       "EINPROGRESS",
                                       "ESTALE",
                                       "EUCLEAN",
                                       "ENOTNAM",
                                       "ENAVAIL",
                                       "EISNAM",
                                       "EREMOTEIO",
                                       "EDQUOT",
                                       "ENOMEDIUM",
                                       "EMEDIUMTYPE",
                                       "ECANCELED",
                                       "ENOKEY",
                                       "EKEYEXPIRED",
                                       "EKEYREVOKED",
                                       "EKEYREJECTED",
                                       "EOWNERDEAD",
                                       "ENOTRECOVERABLE",
                                       "ERFKILL",
                                       "EHWPOISON"};

} // namespace logging
} // namespace ni
